/* tslint:disable */
/* eslint-disable */
/**
 * Java Project Manager VSCode Extension API
 * API for interacting with the Java Project Manager VSCode Extension.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface CommandResponse
 */
export interface CommandResponse {
    /**
     * Status of the command execution (e.g., success, failed).
     * @type {string}
     * @memberof CommandResponse
     */
    'status'?: string;
    /**
     * A message providing more details about the execution.
     * @type {string}
     * @memberof CommandResponse
     */
    'message'?: string;
}
/**
 * 
 * @export
 * @interface NewProjectRequest
 */
export interface NewProjectRequest {
    /**
     * Name of the new project.
     * @type {string}
     * @memberof NewProjectRequest
     */
    'name'?: string;
    /**
     * Path where the project should be created.
     * @type {string}
     * @memberof NewProjectRequest
     */
    'location'?: string;
    /**
     * Initial dependencies for the project.
     * @type {Array<string>}
     * @memberof NewProjectRequest
     */
    'dependencies'?: Array<string>;
}
/**
 * 
 * @export
 * @interface ProjectDetails
 */
export interface ProjectDetails {
    /**
     * Project name.
     * @type {string}
     * @memberof ProjectDetails
     */
    'name'?: string;
    /**
     * Project path.
     * @type {string}
     * @memberof ProjectDetails
     */
    'path'?: string;
    /**
     * List of files in the project.
     * @type {Array<string>}
     * @memberof ProjectDetails
     */
    'files'?: Array<string>;
    /**
     * List of project dependencies.
     * @type {Array<string>}
     * @memberof ProjectDetails
     */
    'dependencies'?: Array<string>;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieves details about the current Java project.
         * @summary Get project details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/project`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Creates a new Java project based on the provided details.
         * @summary Create a new project
         * @param {NewProjectRequest} [newProjectRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectPost: async (newProjectRequest?: NewProjectRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/project`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(newProjectRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieves details about the current Java project.
         * @summary Get project details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async projectGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProjectDetails>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.projectGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.projectGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Creates a new Java project based on the provided details.
         * @summary Create a new project
         * @param {NewProjectRequest} [newProjectRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async projectPost(newProjectRequest?: NewProjectRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.projectPost(newProjectRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.projectPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * Retrieves details about the current Java project.
         * @summary Get project details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectGet(options?: RawAxiosRequestConfig): AxiosPromise<ProjectDetails> {
            return localVarFp.projectGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Creates a new Java project based on the provided details.
         * @summary Create a new project
         * @param {NewProjectRequest} [newProjectRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectPost(newProjectRequest?: NewProjectRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.projectPost(newProjectRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * Retrieves details about the current Java project.
     * @summary Get project details
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public projectGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).projectGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Creates a new Java project based on the provided details.
     * @summary Create a new project
     * @param {NewProjectRequest} [newProjectRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public projectPost(newProjectRequest?: NewProjectRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).projectPost(newProjectRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



